mgm-interns/team-radio-services

pom.xml, src/main/java/com/mgmtp/radio/domain/station/Song.java, src/main/java/com/mgmtp/radio/domain/station/Station.java, src/main/java/com/mgmtp/radio/dto/station/SongDTO.java, src/main/java/com/mgmtp/radio/dto/station/StationDTO.java, src/main/java/com/mgmtp/radio/mapper/decorator/SongMapperDecorator.java, src/main/java/com/mgmtp/radio/mapper/station/SongMapper.java, src/main/java/com/mgmtp/radio/mapper/station/StationMapper.java, src/main/java/com/mgmtp/radio/respository/station/StationRepository.java, src/main/java/com/mgmtp/radio/sdo/StationPrivacy.java, src/main/java/com/mgmtp/radio/sdo/StationPrivacyKeys.java
Hi everybody, I added model and mapper for station. please help me review (type of fields in station if it is correct or not) and merge.
thank you in advance!
=> Add station model

src/main/java/com/mgmtp/radio/controller/v1/FavoriteSongController.java, src/main/java/com/mgmtp/radio/service/user/FavoriteSongServiceImpl.java
hi Mr.Dat, I updated method reference style for favorite song. Please help me review.
=> Update reference method style

src/main/java/com/mgmtp/radio/controller/v1/SongController.java, src/main/java/com/mgmtp/radio/dto/station/SongDTO.java, src/main/java/com/mgmtp/radio/respository/station/SongRepository.java, src/main/java/com/mgmtp/radio/respository/station/StationRepository.java, src/main/java/com/mgmtp/radio/service/station/SongService.java, src/main/java/com/mgmtp/radio/service/station/SongServiceImpl.java, src/main/java/com/mgmtp/radio/service/station/StationService.java, src/main/java/com/mgmtp/radio/service/station/StationServiceImpl.java, src/test/java/com/mgmtp/radio/RadioApplicationTests.java, src/test/java/com/mgmtp/radio/controller/v1/SongControllerTest.java, src/test/java/com/mgmtp/radio/service/station/SongServiceImplTest.java
Dear @dat-ng 
I finished issue 42 [https://github.com/mgm-interns/teamradio2-frontend/issues/42]
Please help me review this.
Thanks!
=> Issue #42_Create API for getting playlist of station

pom.xml, src/main/java/com/mgmtp/radio/aop/UserAspect.java, src/main/java/com/mgmtp/radio/config/ChannelConfig.java, src/main/java/com/mgmtp/radio/config/MailgunConfig.java, src/main/java/com/mgmtp/radio/config/RadioConfig.java, src/main/java/com/mgmtp/radio/domain/mail/Email.java, src/main/java/com/mgmtp/radio/event/MailgunEventEndPoint.java, src/main/java/com/mgmtp/radio/support/MailgunHelper.java, src/main/resources/mailTemplate/register_template.html, src/main/resources/template.properties
Dear @dat-ng 
I finished implement mailgun.
Please help me review.
Thank you.
=> Implement mailgun

src/main/java/com/mgmtp/radio/service/station/SongServiceImpl.java, src/main/java/com/mgmtp/radio/support/YouTubeHelper.java
Handle null pointer exception for YoutubeHelper
=> Fix youtube api handler

src/main/java/com/mgmtp/radio/controller/v1/StationController.java
Hi Mr.Dat, I updated duration time in joining station.
please help me review it.
thank you so much!
=> Update duration for joining station

src/main/java/com/mgmtp/radio/controller/v1/SongController.java, src/main/java/com/mgmtp/radio/domain/station/PlayList.java, src/main/java/com/mgmtp/radio/service/station/SongServiceImpl.java, src/main/java/com/mgmtp/radio/support/StationPlayerHelper.java, src/test/java/com/mgmtp/radio/service/station/SongServiceImplTest.java
Dear @dat-ng 
I fixed stream song.
Please help me review.
Thank you
=> Change stream song

src/main/java/com/mgmtp/radio/controller/v1/StationController.java
hi Mr.Dat, I updated source code which users can not  create station before.
Please help me review and merge. Thank you so much!!
=> Fix can not create station

src/main/java/com/mgmtp/radio/service/station/SongService.java, src/main/java/com/mgmtp/radio/service/station/SongServiceImpl.java, src/main/java/com/mgmtp/radio/service/user/FavoriteSongServiceImpl.java, src/test/java/com/mgmtp/radio/service/user/favorite/CreateFavoriteSongImplTest.java, src/test/java/com/mgmtp/radio/service/user/favorite/DeleteFavoriteSongImplTest.java, src/test/java/com/mgmtp/radio/service/user/favorite/GetFavoriteSongByUserIdImplTest.java
hi Mr.Đạt, I updated add favorite song, I added song bean into FavoriteSongDTO. please help me review and merge.
thank you so much!
=> Update Song bean into FavoriteSongDTO

src/main/java/com/mgmtp/radio/service/station/SongServiceImpl.java
Dear @dat-ng 
I fixed the error when anomyous user add song then playlist will error.
Please help me review it.
Thank you.
=> fix get song not have creator

src/main/java/com/mgmtp/radio/respository/station/SongRepository.java, src/main/java/com/mgmtp/radio/service/station/SongServiceImpl.java, src/main/java/com/mgmtp/radio/service/user/FavoriteSongServiceImpl.java
Hi Mr.Dat, I updated unload data for favorite song.
thank you so much!!
=> Update unload data

src/main/java/com/mgmtp/radio/config/MessageChannelConfig.java, src/main/java/com/mgmtp/radio/controller/v1/SongController.java, src/main/java/com/mgmtp/radio/event/BaseEventMessageEndpoint.java, src/main/java/com/mgmtp/radio/event/HistoryChannelEndpoint.java, src/main/java/com/mgmtp/radio/event/SendVerificationMailEvent.java, src/main/java/com/mgmtp/radio/sdo/EventDataKeys.java, src/main/java/com/mgmtp/radio/sdo/SubscriptionEvents.java, src/main/java/com/mgmtp/radio/service/station/SongServiceImpl.java, src/test/java/com/mgmtp/radio/controller/v1/SongControllerTest.java, src/test/java/com/mgmtp/radio/service/song/SaveSongAfterSkippedTest.java, src/test/java/com/mgmtp/radio/service/station/AddSongServiceImplTest.java, src/test/java/com/mgmtp/radio/service/station/CreateStationImplTest.java, src/test/java/com/mgmtp/radio/service/station/SongServiceImplTest.java, src/test/java/com/mgmtp/radio/service/station/UpVoteAndDownVoteSongServiceImplTest.java
Dear @dat-ng 
I have implement function move song to history.
Please help review and merge it.
Thank you.
=> Move song to history

src/main/java/com/mgmtp/radio/controller/v1/ReputationController.java, src/main/java/com/mgmtp/radio/domain/reputation/Reputation.java, src/main/java/com/mgmtp/radio/dto/reputation/ReputationDTO.java, src/main/java/com/mgmtp/radio/mapper/reputation/ReputationMapper.java, src/main/java/com/mgmtp/radio/respository/reputation/ReputationRepository.java, src/main/java/com/mgmtp/radio/service/reputation/ReputationService.java, src/main/java/com/mgmtp/radio/service/reputation/ReputationServiceImpl.java, src/test/java/com/mgmtp/radio/service/reputation/ReputationImplTest.java
I have finished. Please review.
Required ticket: https://github.com/mgm-interns/teamradio2-frontend/issues/145
=> Create reputation feature

src/main/java/com/mgmtp/radio/service/station/SongServiceImpl.java, src/main/java/com/mgmtp/radio/support/StationPlayerHelper.java
Dear @dat-ng 
I have implement sort for up vote, down vote and add info of vote user for playlist
Please help review and merge it
Thank you
=> Add sort follow vote

src/main/java/com/mgmtp/radio/dto/station/StationDTO.java, src/main/java/com/mgmtp/radio/service/station/StationServiceImpl.java
Fix bug cannot get station configuration to dto
=> Fix station update configuration bug: Cannot retrieve station

src/main/java/com/mgmtp/radio/controller/v1/StationController.java, src/main/java/com/mgmtp/radio/dto/station/StationDTO.java, src/main/java/com/mgmtp/radio/support/validator/station/CreateStationValidator.java
Dear @dat-ng 
I fixed create station.
Please help me review and merge it.
Thank you.
=> fix configuration station

src/main/java/com/mgmtp/radio/service/station/SongServiceImpl.java
Dear @dat-ng 
I fixed bug anonymous user can add song to playlist. Sorry for this.
Please help review and merge it.
Thank you
=> fix anonymous add song

src/main/java/com/mgmtp/radio/schedule/UpdateConversationAvatarJob.java, src/main/java/com/mgmtp/radio/service/conversation/MessageServiceImpl.java, src/main/java/com/mgmtp/radio/service/user/UserServiceImpl.java, src/main/java/com/mgmtp/radio/support/UserHelper.java
Hi Mr.Dat, I updated username of chat. please help me review and merge!
thank you so much!!
=> Update username for chat

src/main/java/com/mgmtp/radio/domain/station/NowPlaying.java, src/main/java/com/mgmtp/radio/service/station/SongServiceImpl.java, src/main/java/com/mgmtp/radio/support/StationPlayerHelper.java
Dear @dat-ng 
I fixed message when skip song and change variable as request from frontend,
Please help review and merge it
Thank you.
=> fix message when skip

src/test/java/com/mgmtp/radio/service/conversation/CreateMessageTest.java, src/test/java/com/mgmtp/radio/service/conversation/FindBySenderUserIdTest.java, src/test/java/com/mgmtp/radio/service/conversation/FindByStationIdTest.java, src/test/java/com/mgmtp/radio/service/conversation/UpdateMessageTest.java
hi Mr.Dat, I updated unit test for chat, please help me review and merge.
=> Update unit test for chat

src/main/java/com/mgmtp/radio/config/MessageChannelConfig.java, src/main/java/com/mgmtp/radio/controller/v1/SongController.java, src/main/java/com/mgmtp/radio/event/UpdateShiftSongChannelEndpoint.java, src/main/java/com/mgmtp/radio/sdo/EventDataKeys.java, src/main/java/com/mgmtp/radio/sdo/SubscriptionEvents.java, src/main/java/com/mgmtp/radio/service/station/SongService.java, src/main/java/com/mgmtp/radio/service/station/SongServiceImpl.java, src/main/java/com/mgmtp/radio/support/StationPlayerHelper.java, src/test/java/com/mgmtp/radio/service/song/SaveSongAfterSkippedTest.java, src/test/java/com/mgmtp/radio/service/station/AddSongServiceImplTest.java, src/test/java/com/mgmtp/radio/service/station/SongServiceImplTest.java, src/test/java/com/mgmtp/radio/service/station/UpVoteAndDownVoteSongServiceImplTest.java
Dear @dat-ng 
I implement seek song when user reconnect to station,
Please help review and merge it
Thank you.
=> Seek playlist when reconnect

src/main/java/com/mgmtp/radio/config/Constant.java, src/main/java/com/mgmtp/radio/controller/v1/StationController.java, src/main/java/com/mgmtp/radio/domain/user/User.java, src/main/java/com/mgmtp/radio/dto/user/UserDTO.java, src/main/java/com/mgmtp/radio/respository/user/UserRepository.java, src/main/java/com/mgmtp/radio/service/station/StationService.java, src/main/java/com/mgmtp/radio/service/user/UserService.java, src/main/java/com/mgmtp/radio/service/user/UserServiceImpl.java, src/main/resources/constants.properties, src/test/java/com/mgmtp/radio/service/user/GetAllMyStationOfUserTest.java, src/test/java/com/mgmtp/radio/service/user/GetAllStationOfSpecificUserById.java, src/test/java/com/mgmtp/radio/service/user/UserServiceImplTest.java
Hi Mr.Dat, I finished joining station with anonymous users. please help me review and merge.
thank you so much!!!!
=> Add anonymous user joining station

src/test/java/com/mgmtp/radio/service/station/CreateStationImplTest.java
Hi Mr.Dat, I finished updating unit test for creating station.
=> Fix create station unit test

src/main/java/com/mgmtp/radio/controller/v1/StationController.java, src/main/java/com/mgmtp/radio/service/station/StationServiceImpl.java, src/main/java/com/mgmtp/radio/support/validator/station/CreateStationValidator.java, src/main/resources/messages.properties
Hi Mr.Dat, I finished fixing a bug which is about creating station with empty spaces. please help me review and merge.
=> Fix bug station when creating with empty spaces

src/main/java/com/mgmtp/radio/controller/v1/StationController.java
Dear @dat-ng 
I remove distinct for station browser, sorry for this
Please review and merge it
Thank you.
=> remove distinct

src/main/java/com/mgmtp/radio/controller/v1/RecentStationController.java
Change from v1/user -> v1/users
=> change recent station endpoint v1/user -> v1/users

src/main/java/com/mgmtp/radio/config/CORSFilter.java, src/main/java/com/mgmtp/radio/config/Constant.java, src/main/java/com/mgmtp/radio/controller/v1/SongController.java, src/main/java/com/mgmtp/radio/controller/v1/StationController.java, src/main/java/com/mgmtp/radio/service/station/SongService.java, src/main/java/com/mgmtp/radio/service/station/SongServiceImpl.java, src/main/java/com/mgmtp/radio/service/user/UserService.java, src/main/java/com/mgmtp/radio/service/user/UserServiceImpl.java, src/main/java/com/mgmtp/radio/support/CookieHelper.java, src/main/resources/constants.properties, src/test/java/com/mgmtp/radio/controller/v1/SongControllerTest.java, src/test/java/com/mgmtp/radio/service/station/AddSongServiceImplTest.java, src/test/java/com/mgmtp/radio/service/user/GetAllMyStationOfUserTest.java, src/test/java/com/mgmtp/radio/service/user/GetAllStationOfSpecificUserById.java, src/test/java/com/mgmtp/radio/service/user/UserServiceImplTest.java
hi Mr.Dat, I implemented creating station with anonymous users.
=> Implement creating station with anonymous user

src/main/java/com/mgmtp/radio/aop/RecentStationAspect.java
Hi Mr.Dat, I handled conflicts with recent stations of Mr.Hau.
Thank you so much!
=> Handle conflict with recent stations

src/main/java/com/mgmtp/radio/sdo/RadioTimeUnit.java, src/main/java/com/mgmtp/radio/support/TransferHelper.java
there is something wrong with converting youtube duration and I fixed it.
https://github.com/mgm-interns/teamradio2-frontend/issues/375
=> Refactor code and fix youtube duration convert

src/main/java/com/mgmtp/radio/domain/user/User.java, src/main/java/com/mgmtp/radio/dto/user/UserDTO.java, src/main/java/com/mgmtp/radio/service/station/SongServiceImpl.java, src/main/java/com/mgmtp/radio/service/user/UserServiceImpl.java
hi Mr.Dat, I updated anonymous username.
=> Update anonymous username

src/main/java/com/mgmtp/radio/aop/UpdateStationConfigAspect.java, src/main/java/com/mgmtp/radio/domain/station/StationConfiguration.java, src/main/java/com/mgmtp/radio/dto/station/StationConfigurationDTO.java, src/main/java/com/mgmtp/radio/dto/station/StationDTO.java, src/main/java/com/mgmtp/radio/service/station/SongService.java, src/main/java/com/mgmtp/radio/service/station/SongServiceImpl.java, src/main/java/com/mgmtp/radio/service/station/StationOnlineServiceImpl.java, src/main/java/com/mgmtp/radio/service/station/StationServiceImpl.java, src/main/resources/application.properties, src/test/java/com/mgmtp/radio/service/station/StationOnlineServiceImplTest.java
Skip anonymous user when count online users
Fix the algorithm of skip rule: Fix the bug song was not skipped when user switch from ADVANCE to BASIC mode and vice versa.
=> skip_anonymous

src/main/java/com/mgmtp/radio/config/MessageChannelConfig.java, src/main/java/com/mgmtp/radio/controller/v1/SongController.java, src/main/java/com/mgmtp/radio/controller/v1/StationController.java, src/main/java/com/mgmtp/radio/dto/station/StationDTO.java, src/main/java/com/mgmtp/radio/service/station/StationOnlineService.java, src/main/java/com/mgmtp/radio/service/station/StationOnlineServiceImpl.java, src/main/java/com/mgmtp/radio/service/station/StationService.java, src/main/java/com/mgmtp/radio/service/station/StationServiceImpl.java, src/main/java/com/mgmtp/radio/support/UserHelper.java, src/test/java/com/mgmtp/radio/controller/v1/SongControllerTest.java
Dear @dat-ng 
I implemented join leave station notification, also fix number online user.
Please help review and merge it
Thank you
=> Add user join leave

src/main/java/com/mgmtp/radio/support/validator/station/CreateStationValidator.java
The error message should be: This station name has been existed
=> Fix station exist error message home page

src/main/java/com/mgmtp/radio/aop/UpdateStationConfigAspect.java, src/main/java/com/mgmtp/radio/controller/v1/MessageController.java, src/main/java/com/mgmtp/radio/controller/v1/StationController.java, src/main/java/com/mgmtp/radio/service/station/SongServiceImpl.java, src/main/java/com/mgmtp/radio/service/station/StationService.java, src/main/java/com/mgmtp/radio/service/station/StationServiceImpl.java
Dear @dat-ng 
I fixed the bug when update config of station then count reset to 0, also seperate link stream station info beside the old one, and temporary limit query of chat api.
Please help review and merge it.
Thank you.
=> Fix station configuration

src/main/java/com/mgmtp/radio/controller/v1/StationController.java, src/main/java/com/mgmtp/radio/service/station/StationServiceImpl.java
Hi Mr.Dat, I updated anonymous station privacy.
thank you so much!
=> change anonymous station privacy

src/main/java/com/mgmtp/radio/aop/UpdateStationConfigAspect.java, src/main/java/com/mgmtp/radio/service/station/SongServiceImpl.java
Dear @dat-ng 
I fixed skip rule not work for whole list when station config changed, also move skip song to history as request from frontend.
Please help review and merge it.
Thank you
=> Fix skip rule when change station config

src/main/java/com/mgmtp/radio/aop/AnonymousUserAspect.java
hi Mr.Dat, I add mapping anonymous users to online stations.
thank you so much!!
=> Map anonymous users to online stations
